	[common.biome]
		MixinBiome = true

	[common.block]
		MixinBlockState = true
		MixinBlockStateBase = true
		MixinBubbleColumnBlock = true
		MixinCopperGrateBlock = true
		MixinFallingBlock = true
		MixinIBlockExtension = true
		MixinLayeredCauldronBlock = true

	[common.chunk]
		MixinAccessorLevelChunkSection = true
		MixinChunkAccess = true
		MixinLevelChunk = true
		MixinPalettedContainer = true
		MixinSimpleBitStorage = true
		MixinZeroBitStorage = true

	[common.command]
		MixinWeatherCommand = true

	[common.entity]
		MixinEntity = true
		MixinLivingEntity = true
		MixinServerPlayer = true

	[common.item]
		MixinMapItem = true

	[common.level]
		MixinDimensionType = true
		MixinLevel = true
		MixinLevelTimeAccess = true
		MixinServerLevel = true

	[common.worldgen]
		MixinSurfaceSystem = true

[data]
	MixinsDataProvider = true
	MixinsDelegatingOps = true
	MixinsDynamicOps = true
	MixinsRegistriesDatapackGenerator = true
	RegistrySetBuilderMixin = true

[game]
	MixinBee_BeePollinateGoal = true
	MixinBeehiveBlockEntity = true
	MixinBreedGoal = true
	MixinCow = true
	MixinFishingHook = true
